### PR TITLE
project LWRP v2

### PR DESCRIPTION
**Pull request by brugidou**
Template and custom executors can be configured. Only SSH is
available as a template.

TODO: FileCopier config

### CODE REVIEW

**Comment by rveznaver** [comment]
The template should be made in a way that it simply generates a valid .properties file format (http://en.wikipedia.org/wiki/.properties) from a given hash. Once created, this template ("properties.erb") should replace both "rundeck-config.properties.erb" and "project.properties.erb". Therefore all key/value generation should be moved inside the recipe, not put in the template.

**Comment by brugidou** [comment]
Done, i added a commit

**Comment by rveznaver** [comment]
The template should take care of escaping #, !, =, and : if they are written in a value.

**Comment by brugidou** [comment]
Let's do that later. For now you can escape properties directly in attributes.

**Pull request merged**
